import * as React from "react";
import {Jumbotron, Table} from "reactstrap";


/**
 * Displays the content for the report
 */
export class Report extends React.Component{

    constructor(props){
        super(props);
        this.state = {showReport1:false, showReport2:false};
    }

    /**
     *  Handles the click event to show the given report
     * @param {The event handler} e 
     */
    handleClick(e){
        if(e.currentTarget.id ==="Report1")
            this.setState({showReport1:!this.state.showReport1});
        else if(e.currentTarget.id === 'Report2')
            this.setState({showReport2:!this.state.showReport2});
    }
    render(){
        return (<div>
            <Jumbotron>
            <h1>Our Report</h1>
            Michael Blithe, Josh Martini, Anton Smolka
            </Jumbotron>
            <div id="Report1" className="p-3 mb-2 bg-primary text-white" style={{borderRadius:10}} onClick={this.handleClick.bind(this)}>
                    Analysis of School Performance Data Using Machine Learning

            </div>

            {this.state.showReport1?(
                <div>
                    <div className="p-3 mb-2 bg-primary text-white" style={{ textAlign: "center" }}>
						<h1 id="definitions-and-methodology">Definitions and Methodology</h1>
						<p>This analysis was performed using a variety of machine learning techniques with data from government sources. The first machine learning technique used was random forest decision trees. This method trains a collection of decision trees that vote on the data to obtain a result. A simple decision tree may take the form of deciding whether or not to wear shorts or long pants. It may state that if the temperature is above 70 degrees fahrenheit, the person will wear shorts. Several hundred of these trees are trained on a small portion of the data and the trees then vote on the result. This technique can also rank the importance of the attributes. The next machine learning tool used is a neural network. This works like the brain. It has a collection of neurons which create an output based off some internal weight when given an input. This weight is adjusted during the training process on the data. Finally, genetic algorithms are used. This algorithm draws from evolution in biology. A random population of organisms, or in this case hypothetical schools, are created and these “organisms” are combined to eventually produce a result. The performance of these hypothetical schools was created using a neural network.</p>
						<h1 id="selected-results">Selected Results</h1>
						<h2 id="location">Location</h2>
						<p>The location of the schools created by the genetic algorithms appeared in only a few states. In particular, the schools primarily appeared in Iowa, Pennsylvania and, New York, as well as a few additional states. These states appear to be darker in the actual school data, meaning higher performance on the tests. Latitude, longitude, and state account for three of the top ten features in terms of importance as assigned by the random forest tree.</p>
                        <h4> Figure 1: Performance of Schools Generated by Genetic Algorithm </h4>
                        <p><img className="img-fluid" src={process.env.PUBLIC_URL + "/images/GeneticMap.png"} alt="The schools created by the genetic algorithm. Darker means higher scores" /> The Performance of the Schools Created by the Genetic Algorithm. Darker Means Higher Test Scores.</p>
                        <h4> Figure 2: Performance of Schools in Actual Data </h4>
                        <p><img className="img-fluid" src={process.env.PUBLIC_URL + "/images/actualMap.png"} alt="The schools created by the genetic algorithm. Darker means higher scores" /> The School Performance from the Government Data. Darker Means Higher Test Scores.</p>
						<h2 id="student-to-teacher-ratios">Student to Teacher Ratios</h2>
						<p>As shown in figure 3 the schools the genetic algorithm created each have very low student to teacher ratios, while the actual schools have much higher student to teacher ratios. This shows that student to teacher ratios are highly significant. This is confirmed by the random forest decision tree, which determined the student to teacher ratio to be significant.</p>
                        <h4> Figure 3: Student to Teacher Ratios</h4>
                        <p><img src={process.env.PUBLIC_URL + "/images/read_full_time_cropped.png"} className="img-fluid" /></p>
						<h2 id="title-i">Title I</h2>
						<p>The most significant attribute for a school according to the random forest decision tree was whether or not the school receives schoolwide funding from Title I. Title I is a federal funding program. This program provides funds to schools with a high number of children of low-income families to help them achieve academic standards. As shown in figure 4 the schools created by the genetic algorithms almost unanimously do not receive Title I money. The reason for this result requires further research.</p>
                        <h4> Figure 4: Schoolwide Title I Eligibility </h4>
                        <p><img src={process.env.PUBLIC_URL + "/images/school_wide_title_i_eligibility_Yes.png"} className="img-fluid" /></p>
						<h2 id="number-of-students">Number of Students</h2>
						<p>As seen in figure 5, the schools created by the genetic algorithm tend to have a higher number of students than real schools. However, as discussed above the hypothetical schools maintain a low student to teacher ratio by employing many faculty thus, meaning that having more students can be beneficial, but only if there is the teaching staff to adequately support those students. These numbers were extrapolated from the number of students who took and were assigned a proficiency score for the math portion of the standardized test.</p>
                        <h4> Figure 5: Number of Students</h4>
                        <p><img src={process.env.PUBLIC_URL + "/images/math_all_grades_numvalid_cropped.png"} className="img-fluid" /></p>
						<h2 id="per-pupil-spending">Per Pupil Spending</h2>
						<p>It was discovered that the amount of money spent per student, as well as the total amount spent, had less impact on performance. This was discovered using a decision tree to rank the importance of each attribute of the school.</p>
                    </div>
                </div>
            ):null}
            <div id="Report2" className="p-3 mb-2 bg-primary text-white" style={{borderRadius:10}} onClick={this.handleClick.bind(this)}>
                Analysis of School Performance Data Using Statistical Analysis 
            </div>

            {this.state.showReport2?(
            <div>
                
                    <div className="p-3 mb-2 bg-primary text-white" style={{ textAlign: "center" }}>
                        <h1>Proficiency Breakdown </h1>
                        <p> The biggest note is that not all schools from the data could be broken down by by proficiency level. </p>
                        <p> Reading 97% Captured </p>
                        <p> Math 95.6% Captured </p>
                        <h4> Table I: Proficency Levels </h4>
                        <Table bordered dark>
                            <thead>
                                <tr> <td>Proficency Level </td> <td>Reading </td> <td> Percentage of Total Reading Schools </td> <td> Math </td> <td> Percentage of Total Math Schools </td> </tr>
                            </thead>
                            <tbody>

                                <tr> <td>0 - 25</td> <td>10,329</td> <td>11.40%</td> <td>16,425</td> <td>18.00%</td> </tr>

                                <tr> <td>26 - 50</td> <td>30,748</td> <td>34.00%</td> <td>29562</td> <td>32.60%</td> </tr>

                                <tr> <td>51 - 75</td> <td>30,937</td> <td>34.00%</td> <td>25,807</td> <td>28.40%</td> </tr>

                                <tr> <td>76 - 100</td> <td>15,942</td> <td>17.60%</td> <td>15,090</td> <td>16.60%</td> </tr>

                                <tr> <td>Total ReadingSchools</td> <td>87,956</td> <td>Total Math Schools </td> <td>86,884</td> <td> </td> </tr>
                            </tbody>

                        </Table>
                        <h1>Funding Compare Between Top/Worst Schools </h1>
                        <p>The funding looks at the per pupil spending data provided in the Funding dataset. The per pupil spending data is derived by the current spending per school district/ the #  of students enrolled in that school district. The current spending is defined as the amount of money the school district receives  for spending on salaries, benefits, purchased service, property, and supplies.  </p>
                        <p>Overall Average Per Pupil Spending for ALL School Districts is $13,185.78 </p>
                        <p> Range ($0 - $5,320,000) </p>
                        <p> The focus of this analysis was to look at and understand why particular schools fail standardized tests scores at a high rate.  To isolate the school districts which we are focusing on, schools were filtered such that they had a proficiency level of 25% or less in both Reading in Math scores. This yielded a total of 7,297 schools into this category. Since we are looking at school districts and not individual schools, a threshold of school districts with at least 3 failing schools in this category was applied. This yielded an answer of 5,058 schools.  </p>
                        <p> The average FAILING (25% or Lower) Per Pupil Spending for school districts is <strong>$12,678.38</strong></p>
                        <p> Range ($ 5,841 - 76, 777) </p>
                        <p> Table II and Table III highlights the top 7 schools districts with school the highest amounts of schools falling at a 25 % or lower rate. In total there this is 860 Schools. This is 12% of our original 7,297 number and 17% of our 5,058 number! Moreover, 5 out of the 7 worst performing school districts actually have a HIGHER per pupil spending than our failing rate highlighted above.  </p>
                        <p> To get a comparison to the numbers, the data was rearranged such that schools which passed at a 75% or higher rate in Reading and Math was displayed.  In total there were 10,538 which fell into this category. Again the same process was done on these numbers and below are the results.  </p>
                        <p> The age PASSING (75% or Above) per pupil spending for school districts is <strong> $13,489.77 </strong> </p>
                        <p> Range ($0 - $270,059) </p>
                        <p> Looking school districts with the top 7 passing schools (478 total) 5 out of the 7 have a lower Per Pupil Spending than our Failing Average. </p>
                        <h4 > Table II: Funding Breakdown for School Districts with Schools That Passed at a 75 % or High Clip in Math and Reading </h4>
                        <Table dark bordered>
                            <thead>
                                <tr> <td>Funding_ID</td> <td>Pupil Spending</td> <td>Curent Speding</td> <td>District Name</td> <td>Number of Schools </td> </tr>
                            </thead>
                            <tbody>
                                <tr> <td>5101260</td> <td>13,991.00</td> <td>2,612,731.00</td> <td>FAIRFAX CO SCHS</td> <td>115</td> </tr>
                                <tr> <td>4823640</td> <td>9,633.00</td> <td>2,088,095.00</td> <td>HOUSTON IND SCH DIST 912</td> <td>69</td> </tr>
                                <tr> <td>4820010</td> <td>7,722.00</td> <td>413,002.00</td> <td>FRISCO INDEP SCH DISTRICT 905</td> <td>63</td> </tr>
                                <tr> <td>4833120</td> <td>8,329.00</td> <td>881,734.00</td> <td>NORTHSIDE IND SCH DIST 915</td> <td>59</td> </tr>
                                <tr> <td>1200390</td> <td>8,938.00</td> <td>3,282,648.00</td> <td>MIAMI-DADE COUNTY PUBLIC SCHOOL DISTRICT</td> <td>59</td> </tr>
                                <tr> <td>5103840</td> <td>10,920.00</td> <td>764,264.00</td> <td>VIRGINIA BEACH CITY SCHS</td> <td>58</td> </tr>
                                <tr> <td>5102250</td> <td>13,394.00</td> <td>1,021,240.00</td> <td>LOUDOUN CO SCHS</td> <td>55</td> </tr>
                                <tr> <td>Total Schools = 10,538</td> <td></td> <td></td> <td>Total</td> <td>478</td> </tr>
                            </tbody>
                        </Table>
                        <br />
                        <h4> Table III: Funding Breakdown for School Districts with Schools That Passed at a 25 % or Lower Clip in Math and Reading</h4>
                        <Table dark bordered>
                            <thead>
                                <tr> <td>Funding_ID</td> <td>Pupil Spending</td> <td>Curent Speding</td> <td>District Name</td> <td>Number of Schools</td> </tr>
                            </thead>
                            <tbody>
                                <tr> <td>1709930</td> <td>13,453.00</td> <td>5,332,893.00</td> <td>CITY OF CHICAGO SCHOOL DISTRICT 299</td> <td>279</td> </tr>
                                <tr> <td>622710</td> <td>13,230.00</td> <td>8,558,578.00</td> <td>LOS ANGELES UNIF SCH DIST</td> <td>173</td> </tr>
                                <tr> <td>4700148</td> <td>9,774.00</td> <td>1,130,779.00</td> <td>SHELBY COUNTY SCHOOL DISTRICT</td> <td>86</td> </tr>
                                <tr> <td>5509600</td> <td>12,714.00</td> <td>990,554.00</td> <td>MILWAUKEE CITY SCHOOL DISTRICT</td> <td>86</td> </tr>
                                <tr> <td>2400510</td> <td>14,851.00</td> <td>1,918,402.00</td> <td>PRINCE GEORGES CO SCHS</td> <td>85</td> </tr>
                                <tr> <td>2400090</td> <td>15,168.00</td> <td>1,269,079.00</td> <td>BALTIMORE CITY SCHOOLS</td> <td>83</td> </tr>
                                <tr> <td>4218990</td> <td>11,396.00</td> <td>2,266,231.00</td> <td>PHILADELPHIA SCHOOL DISTRICT</td> <td>68</td> </tr>
                                <tr> <td>Total Schools = 7,297</td> <td></td> <td></td> <td>Total </td> <td>860</td> </tr>
                            </tbody>
                        </Table>
                        <h1> Teacher Breakdown Top/Worst Schools </h1>
                        <p> These are the same school districts which are were compared in the section above. This section is finding the average number of teachers per school in the respected school district.  </p>
                        <p> The results: NOT 1 of the passing schools had a lower average number of teachers than the failing schools. </p>
                        <h4> Table IV: Top Schools: Average Teachers Per School in District</h4>
                        <Table dark bordered>
                            <thead>
                                <tr> <td>District Name</td> <td>Average Teachers Per School in District </td> </tr>
                            </thead>
                            <tbody>
                                <tr> <td>FAIRFAX CO SCHS</td> <td>64</td> </tr>
                                <tr> <td>HOUSTON IND SCH DIST 912</td> <td>41</td> </tr>
                                <tr> <td>FRISCO INDEP SCH DISTRICT 905</td> <td>57</td> </tr>
                                <tr> <td>NORTHSIDE IND SCH DIST 915</td> <td>59</td> </tr>
                                <tr> <td>MIAMI-DADE COUNTY PUBLIC SCHOOL DISTRICT</td> <td>42</td> </tr>
                                <tr> <td>VIRGINIA BEACH CITY SCHS</td> <td>41</td> </tr>
                                <tr> <td>LOUDOUN CO SCHS</td> <td>49</td> </tr>
                            </tbody>
                        </Table>
                        <h4> Table V: Bottom Schools: Average Teachers Per School in District</h4>
                        <Table dark bordered>
                            <thead>
                                <tr> <td>District Name</td> <td>Average Teachers Per School in District</td> </tr>
                            </thead>
                            <tbody>
                                <tr> <td>CITY OF CHICAGO SCHOOL DISTRICT 299</td> <td>35</td> </tr>
                                <tr> <td>LOS ANGELES UNIF SCH DIST</td> <td>25</td> </tr>
                                <tr> <td>SHELBY COUNTY SCHOOL DISTRICT</td> <td>35</td> </tr>
                                <tr> <td>MILWAUKEE CITY SCHOOL DISTRICT</td> <td>29</td> </tr>
                                <tr> <td>PRINCE GEORGES CO SCHS</td> <td>40</td> </tr>
                                <tr> <td>BALTIMORE CITY SCHOOLS</td> <td>30</td> </tr>
                                <tr> <td>PHILADELPHIA SCHOOL DISTRICT</td> <td>34</td> </tr>
                            </tbody>

                        </Table>
                        <h1> Conclusion   </h1>
                        <p> Money per student or money a school receives has little to no indication of how well a school performs on standardized testing. Not only is the differential between the average per pupil spending number between passing and failing schools minimal, BUT 5 out the 7 best passing school districts actually have less money per student (thousands of dollars) than the schools that are failing at a rate of 25 % or less in math and reading. A better indicator would by the average student to teacher ratio of that school district. Ultimately, failing school districts need to reassess their resources and how they are spending their money, because it appears they have the money to higher on more teachers. </p>
                    </div>
            </div>
            ):null}
        </div>);

    }
}
