using System;
using System.Collections.Generic;

namespace SeniorProjectWebsite.Models
{
    public partial class Math
    {
        public string MathStnam { get; set; }
        public int? MathFipst { get; set; }
        public int? MathLeaid { get; set; }
        public string MathStLeaid { get; set; }
        public string MathLeanm { get; set; }
        public long MathNcessch { get; set; }
        public string MathStSchid { get; set; }
        public string MathSchnam { get; set; }
        public int? MathAllGradesNumvalid { get; set; }
        public int? MathNativeAmericanAllGradesNumvalid { get; set; }
        public int? MathAsianPacificIslanderAllGradesNumvalid { get; set; }
        public int? MathBlackAllGradesNumvalid { get; set; }
        public int? MathHispanicAllGradesNumvalid { get; set; }
        public int? MathMoreThanTwoRacesAllGradesNumvalid { get; set; }
        public int? MathWhiteAllGradesNumvalid { get; set; }
        public int? MathFAllGradesNumvalid { get; set; }
        public int? MathMAllGradesNumvalid { get; set; }
        public int? MathChildrenWithDisabilitesAllGradesNumvalid { get; set; }
        public int? MathPoorAllGradesNumvalid { get; set; }
        public int? MathLimitedEnglishAllGradesNumvalid { get; set; }
        public int? MathHomelessAllGradesNumvalid { get; set; }
        public int? MathMigrantAllGradesNumvalid { get; set; }
        public int? MathAll03numvalid { get; set; }
        public int? MathAll04numvalid { get; set; }
        public int? MathAll05numvalid { get; set; }
        public int? MathAll06numvalid { get; set; }
        public int? MathAll07numvalid { get; set; }
        public int? MathAll08numvalid { get; set; }
        public int? MathAllhsnumvalid { get; set; }
        public int? MathNativeAmerican03numvalid { get; set; }
        public int? MathNativeAmerican04numvalid { get; set; }
        public int? MathNativeAmerican05numvalid { get; set; }
        public int? MathNativeAmerican06numvalid { get; set; }
        public int? MathNativeAmerican07numvalid { get; set; }
        public int? MathNativeAmerican08numvalid { get; set; }
        public int? MathNativeAmericanhsnumvalid { get; set; }
        public int? MathAsianPacificIslander03numvalid { get; set; }
        public int? MathAsianPacificIslander04numvalid { get; set; }
        public int? MathAsianPacificIslander05numvalid { get; set; }
        public int? MathAsianPacificIslander06numvalid { get; set; }
        public int? MathAsianPacificIslander07numvalid { get; set; }
        public int? MathAsianPacificIslander08numvalid { get; set; }
        public int? MathAsianPacificIslanderHsnumvalid { get; set; }
        public int? MathBlack03numvalid { get; set; }
        public int? MathBlack04numvalid { get; set; }
        public int? MathBlack05numvalid { get; set; }
        public int? MathBlack06numvalid { get; set; }
        public int? MathBlack07numvalid { get; set; }
        public int? MathBlack08numvalid { get; set; }
        public int? MathBlackhsnumvalid { get; set; }
        public int? MathHispanic03numvalid { get; set; }
        public int? MathHispanic04numvalid { get; set; }
        public int? MathHispanic05numvalid { get; set; }
        public int? MathHispanic06numvalid { get; set; }
        public int? MathHispanic07numvalid { get; set; }
        public int? MathHispanic08numvalid { get; set; }
        public int? MathHispanichsnumvalid { get; set; }
        public int? MathMoreThanTwoRaces03numvalid { get; set; }
        public int? MathMoreThanTwoRaces04numvalid { get; set; }
        public int? MathMoreThanTwoRaces05numvalid { get; set; }
        public int? MathMoreThanTwoRaces06numvalid { get; set; }
        public int? MathMoreThanTwoRaces07numvalid { get; set; }
        public int? MathMoreThanTwoRaces08numvalid { get; set; }
        public int? MathMoreThanTwoRaceshsnumvalid { get; set; }
        public int? MathWhite03numvalid { get; set; }
        public int? MathWhite04numvalid { get; set; }
        public int? MathWhite05numvalid { get; set; }
        public int? MathWhite06numvalid { get; set; }
        public int? MathWhite07numvalid { get; set; }
        public int? MathWhite08numvalid { get; set; }
        public int? MathWhitehsnumvalid { get; set; }
        public int? MathF03numvalid { get; set; }
        public int? MathF04numvalid { get; set; }
        public int? MathF05numvalid { get; set; }
        public int? MathF06numvalid { get; set; }
        public int? MathF07numvalid { get; set; }
        public int? MathF08numvalid { get; set; }
        public int? MathFhsnumvalid { get; set; }
        public int? MathM03numvalid { get; set; }
        public int? MathM04numvalid { get; set; }
        public int? MathM05numvalid { get; set; }
        public int? MathM06numvalid { get; set; }
        public int? MathM07numvalid { get; set; }
        public int? MathM08numvalid { get; set; }
        public int? MathMhsnumvalid { get; set; }
        public int? MathChildrenWithDisabilites03numvalid { get; set; }
        public int? MathChildrenWithDisabilites04numvalid { get; set; }
        public int? MathChildrenWithDisabilites05numvalid { get; set; }
        public int? MathChildrenWithDisabilites06numvalid { get; set; }
        public int? MathChildrenWithDisabilites07numvalid { get; set; }
        public int? MathChildrenWithDisabilites08numvalid { get; set; }
        public int? MathChildrenWithDisabiliteshsnumvalid { get; set; }
        public int? MathPoor03numvalid { get; set; }
        public int? MathPoor04numvalid { get; set; }
        public int? MathPoor05numvalid { get; set; }
        public int? MathPoor06numvalid { get; set; }
        public int? MathPoor07numvalid { get; set; }
        public int? MathPoor08numvalid { get; set; }
        public int? MathPoorhsnumvalid { get; set; }
        public int? MathLimitedEnglish03numvalid { get; set; }
        public int? MathLimitedEnglish04numvalid { get; set; }
        public int? MathLimitedEnglish05numvalid { get; set; }
        public int? MathLimitedEnglish06numvalid { get; set; }
        public int? MathLimitedEnglish07numvalid { get; set; }
        public int? MathLimitedEnglish08numvalid { get; set; }
        public int? MathLimitedEnglishhsnumvalid { get; set; }
        public int? MathHomeless03numvalid { get; set; }
        public int? MathHomeless04numvalid { get; set; }
        public int? MathHomeless05numvalid { get; set; }
        public int? MathHomeless06numvalid { get; set; }
        public int? MathHomeless07numvalid { get; set; }
        public int? MathHomeless08numvalid { get; set; }
        public int? MathHomelesshsnumvalid { get; set; }
        public int? MathMigrant03numvalid { get; set; }
        public int? MathMigrant04numvalid { get; set; }
        public int? MathMigrant05numvalid { get; set; }
        public int? MathMigrant06numvalid { get; set; }
        public int? MathMigrant07numvalid { get; set; }
        public int? MathMigrant08numvalid { get; set; }
        public int? MathMigranthsnumvalid { get; set; }
        public int? MathAll03pctprofLow { get; set; }
        public int? MathAll03pctprofHigh { get; set; }
        public int? MathAll04pctprofLow { get; set; }
        public int? MathAll04pctprofHigh { get; set; }
        public int? MathAll05pctprofLow { get; set; }
        public int? MathAll05pctprofHigh { get; set; }
        public int? MathAll06pctprofLow { get; set; }
        public int? MathAll06pctprofHigh { get; set; }
        public int? MathAll07pctprofLow { get; set; }
        public int? MathAll07pctprofHigh { get; set; }
        public int? MathAll08pctprofLow { get; set; }
        public int? MathAll08pctprofHigh { get; set; }
        public int? MathAllGradesPctprofLow { get; set; }
        public int? MathAllGradesPctprofHigh { get; set; }
        public int? MathAllhspctprofLow { get; set; }
        public int? MathAllhspctprofHigh { get; set; }
        public int? MathAsianPacificIslander03pctprofLow { get; set; }
        public int? MathAsianPacificIslander03pctprofHigh { get; set; }
        public int? MathAsianPacificIslander04pctprofLow { get; set; }
        public int? MathAsianPacificIslander04pctprofHigh { get; set; }
        public int? MathAsianPacificIslander05pctprofLow { get; set; }
        public int? MathAsianPacificIslander05pctprofHigh { get; set; }
        public int? MathAsianPacificIslander06pctprofLow { get; set; }
        public int? MathAsianPacificIslander06pctprofHigh { get; set; }
        public int? MathAsianPacificIslander07pctprofLow { get; set; }
        public int? MathAsianPacificIslander07pctprofHigh { get; set; }
        public int? MathAsianPacificIslander08pctprofLow { get; set; }
        public int? MathAsianPacificIslander08pctprofHigh { get; set; }
        public int? MathAsianPacificIslanderAllGradesPctprofLow { get; set; }
        public int? MathAsianPacificIslanderAllGradesPctprofHigh { get; set; }
        public int? MathAsianPacificIslanderHspctprofLow { get; set; }
        public int? MathAsianPacificIslanderHspctprofHigh { get; set; }
        public int? MathBlack03pctprofLow { get; set; }
        public int? MathBlack03pctprofHigh { get; set; }
        public int? MathBlack04pctprofLow { get; set; }
        public int? MathBlack04pctprofHigh { get; set; }
        public int? MathBlack05pctprofLow { get; set; }
        public int? MathBlack05pctprofHigh { get; set; }
        public int? MathBlack06pctprofLow { get; set; }
        public int? MathBlack06pctprofHigh { get; set; }
        public int? MathBlack07pctprofLow { get; set; }
        public int? MathBlack07pctprofHigh { get; set; }
        public int? MathBlack08pctprofLow { get; set; }
        public int? MathBlack08pctprofHigh { get; set; }
        public int? MathBlackAllGradesPctprofLow { get; set; }
        public int? MathBlackAllGradesPctprofHigh { get; set; }
        public int? MathBlackhspctprofLow { get; set; }
        public int? MathBlackhspctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites03pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites03pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites04pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites04pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites05pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites05pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites06pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites06pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites07pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites07pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilites08pctprofLow { get; set; }
        public int? MathChildrenWithDisabilites08pctprofHigh { get; set; }
        public int? MathChildrenWithDisabilitesAllGradesPctprofLow { get; set; }
        public int? MathChildrenWithDisabilitesAllGradesPctprofHigh { get; set; }
        public int? MathChildrenWithDisabiliteshspctprofLow { get; set; }
        public int? MathChildrenWithDisabiliteshspctprofHigh { get; set; }
        public int? MathF03pctprofLow { get; set; }
        public int? MathF03pctprofHigh { get; set; }
        public int? MathF04pctprofLow { get; set; }
        public int? MathF04pctprofHigh { get; set; }
        public int? MathF05pctprofLow { get; set; }
        public int? MathF05pctprofHigh { get; set; }
        public int? MathF06pctprofLow { get; set; }
        public int? MathF06pctprofHigh { get; set; }
        public int? MathF07pctprofLow { get; set; }
        public int? MathF07pctprofHigh { get; set; }
        public int? MathF08pctprofLow { get; set; }
        public int? MathF08pctprofHigh { get; set; }
        public int? MathFAllGradesPctprofLow { get; set; }
        public int? MathFAllGradesPctprofHigh { get; set; }
        public int? MathFhspctprofLow { get; set; }
        public int? MathFhspctprofHigh { get; set; }
        public int? MathHispanic03pctprofLow { get; set; }
        public int? MathHispanic03pctprofHigh { get; set; }
        public int? MathHispanic04pctprofLow { get; set; }
        public int? MathHispanic04pctprofHigh { get; set; }
        public int? MathHispanic05pctprofLow { get; set; }
        public int? MathHispanic05pctprofHigh { get; set; }
        public int? MathHispanic06pctprofLow { get; set; }
        public int? MathHispanic06pctprofHigh { get; set; }
        public int? MathHispanic07pctprofLow { get; set; }
        public int? MathHispanic07pctprofHigh { get; set; }
        public int? MathHispanic08pctprofLow { get; set; }
        public int? MathHispanic08pctprofHigh { get; set; }
        public int? MathHispanicAllGradesPctprofLow { get; set; }
    }
}
