const requestMath = "REQUEST_MATH";

const initalState = {Math_Scores:undefined};

export const actionCreators = {
    requestMath:ncessch => async (dispatch, getState)=>{
        const url = `api/Math/${ncessch}`;
        const response = await fetch(url);
        //TODO: Add Error Handling
        const scores = await response.json();
        dispatch({type:requestMath, Math_Scores:scores});
    }
}


/**
 * @function reducer handles the actions generated by the action creates and
 * updates that state as needed.
 */
export const reducer = (state, action)=>{
    switch(action.type){
        case requestMath:
        return {...state, Math_Scores:action.Math_Scores};
        default:
        return state || initalState;
    }
}
