using System;
using System.Collections.Generic;

namespace SeniorProjectWebsite
{
    public partial class Read
    {
        public string ReadStnam { get; set; }
        public int? ReadFipst { get; set; }
        public int? ReadLeaid { get; set; }
        public string ReadStLeaid { get; set; }
        public string ReadLeanm { get; set; }
        public long ReadNcessch { get; set; }
        public string ReadStSchid { get; set; }
        public string ReadSchnam { get; set; }
        public int? ReadAllGradesNumvalid { get; set; }
        public int? ReadNativeAmericanAllGradesNumvalid { get; set; }
        public int? ReadAsianPacificIslanderAllGradesNumvalid { get; set; }
        public int? ReadBlackAllGradesNumvalid { get; set; }
        public int? ReadHispanicAllGradesNumvalid { get; set; }
        public int? ReadMoreThanTwoRacesAllGradesNumvalid { get; set; }
        public int? ReadWhiteAllGradesNumvalid { get; set; }
        public int? ReadFAllGradesNumvalid { get; set; }
        public int? ReadMAllGradesNumvalid { get; set; }
        public int? ReadChildrenWithDisabilitesAllGradesNumvalid { get; set; }
        public int? ReadPoorAllGradesNumvalid { get; set; }
        public int? ReadLimitedEnglishAllGradesNumvalid { get; set; }
        public int? ReadHomelessAllGradesNumvalid { get; set; }
        public int? ReadMigrantAllGradesNumvalid { get; set; }
        public int? ReadAll03numvalid { get; set; }
        public int? ReadAll04numvalid { get; set; }
        public int? ReadAll05numvalid { get; set; }
        public int? ReadAll06numvalid { get; set; }
        public int? ReadAll07numvalid { get; set; }
        public int? ReadAll08numvalid { get; set; }
        public int? ReadAllhsnumvalid { get; set; }
        public int? ReadNativeAmerican03numvalid { get; set; }
        public int? ReadNativeAmerican04numvalid { get; set; }
        public int? ReadNativeAmerican05numvalid { get; set; }
        public int? ReadNativeAmerican06numvalid { get; set; }
        public int? ReadNativeAmerican07numvalid { get; set; }
        public int? ReadNativeAmerican08numvalid { get; set; }
        public int? ReadNativeAmericanhsnumvalid { get; set; }
        public int? ReadAsianPacificIslander03numvalid { get; set; }
        public int? ReadAsianPacificIslander04numvalid { get; set; }
        public int? ReadAsianPacificIslander05numvalid { get; set; }
        public int? ReadAsianPacificIslander06numvalid { get; set; }
        public int? ReadAsianPacificIslander07numvalid { get; set; }
        public int? ReadAsianPacificIslander08numvalid { get; set; }
        public int? ReadAsianPacificIslanderHsnumvalid { get; set; }
        public int? ReadBlack03numvalid { get; set; }
        public int? ReadBlack04numvalid { get; set; }
        public int? ReadBlack05numvalid { get; set; }
        public int? ReadBlack06numvalid { get; set; }
        public int? ReadBlack07numvalid { get; set; }
        public int? ReadBlack08numvalid { get; set; }
        public int? ReadBlackhsnumvalid { get; set; }
        public int? ReadHispanic03numvalid { get; set; }
        public int? ReadHispanic04numvalid { get; set; }
        public int? ReadHispanic05numvalid { get; set; }
        public int? ReadHispanic06numvalid { get; set; }
        public int? ReadHispanic07numvalid { get; set; }
        public int? ReadHispanic08numvalid { get; set; }
        public int? ReadHispanichsnumvalid { get; set; }
        public int? ReadMoreThanTwoRaces03numvalid { get; set; }
        public int? ReadMoreThanTwoRaces04numvalid { get; set; }
        public int? ReadMoreThanTwoRaces05numvalid { get; set; }
        public int? ReadMoreThanTwoRaces06numvalid { get; set; }
        public int? ReadMoreThanTwoRaces07numvalid { get; set; }
        public int? ReadMoreThanTwoRaces08numvalid { get; set; }
        public int? ReadMoreThanTwoRaceshsnumvalid { get; set; }
        public int? ReadWhite03numvalid { get; set; }
        public int? ReadWhite04numvalid { get; set; }
        public int? ReadWhite05numvalid { get; set; }
        public int? ReadWhite06numvalid { get; set; }
        public int? ReadWhite07numvalid { get; set; }
        public int? ReadWhite08numvalid { get; set; }
        public int? ReadWhitehsnumvalid { get; set; }
        public int? ReadF03numvalid { get; set; }
        public int? ReadF04numvalid { get; set; }
        public int? ReadF05numvalid { get; set; }
        public int? ReadF06numvalid { get; set; }
        public int? ReadF07numvalid { get; set; }
        public int? ReadF08numvalid { get; set; }
        public int? ReadFhsnumvalid { get; set; }
        public int? ReadM03numvalid { get; set; }
        public int? ReadM04numvalid { get; set; }
        public int? ReadM05numvalid { get; set; }
        public int? ReadM06numvalid { get; set; }
        public int? ReadM07numvalid { get; set; }
        public int? ReadM08numvalid { get; set; }
        public int? ReadMhsnumvalid { get; set; }
        public int? ReadChildrenWithDisabilites03numvalid { get; set; }
        public int? ReadChildrenWithDisabilites04numvalid { get; set; }
        public int? ReadChildrenWithDisabilites05numvalid { get; set; }
        public int? ReadChildrenWithDisabilites06numvalid { get; set; }
        public int? ReadChildrenWithDisabilites07numvalid { get; set; }
        public int? ReadChildrenWithDisabilites08numvalid { get; set; }
        public int? ReadChildrenWithDisabiliteshsnumvalid { get; set; }
        public int? ReadPoor03numvalid { get; set; }
        public int? ReadPoor04numvalid { get; set; }
        public int? ReadPoor05numvalid { get; set; }
        public int? ReadPoor06numvalid { get; set; }
        public int? ReadPoor07numvalid { get; set; }
        public int? ReadPoor08numvalid { get; set; }
        public int? ReadPoorhsnumvalid { get; set; }
        public int? ReadLimitedEnglish03numvalid { get; set; }
        public int? ReadLimitedEnglish04numvalid { get; set; }
        public int? ReadLimitedEnglish05numvalid { get; set; }
        public int? ReadLimitedEnglish06numvalid { get; set; }
        public int? ReadLimitedEnglish07numvalid { get; set; }
        public int? ReadLimitedEnglish08numvalid { get; set; }
        public int? ReadLimitedEnglishhsnumvalid { get; set; }
        public int? ReadHomeless03numvalid { get; set; }
        public int? ReadHomeless04numvalid { get; set; }
        public int? ReadHomeless05numvalid { get; set; }
        public int? ReadHomeless06numvalid { get; set; }
        public int? ReadHomeless07numvalid { get; set; }
        public int? ReadHomeless08numvalid { get; set; }
        public int? ReadHomelesshsnumvalid { get; set; }
        public int? ReadMigrant03numvalid { get; set; }
        public int? ReadMigrant04numvalid { get; set; }
        public int? ReadMigrant05numvalid { get; set; }
        public int? ReadMigrant06numvalid { get; set; }
        public int? ReadMigrant07numvalid { get; set; }
        public int? ReadMigrant08numvalid { get; set; }
        public int? ReadMigranthsnumvalid { get; set; }
        public int? ReadAll03pctprofLow { get; set; }
        public int? ReadAll03pctprofHigh { get; set; }
        public int? ReadAll04pctprofLow { get; set; }
        public int? ReadAll04pctprofHigh { get; set; }
        public int? ReadAll05pctprofLow { get; set; }
        public int? ReadAll05pctprofHigh { get; set; }
        public int? ReadAll06pctprofLow { get; set; }
        public int? ReadAll06pctprofHigh { get; set; }
        public int? ReadAll07pctprofLow { get; set; }
        public int? ReadAll07pctprofHigh { get; set; }
        public int? ReadAll08pctprofLow { get; set; }
        public int? ReadAll08pctprofHigh { get; set; }
        public int? ReadAllGradesPctprofLow { get; set; }
        public int? ReadAllGradesPctprofHigh { get; set; }
        public int? ReadAllhspctprofLow { get; set; }
        public int? ReadAllhspctprofHigh { get; set; }
        public int? ReadAsianPacificIslander03pctprofLow { get; set; }
        public int? ReadAsianPacificIslander03pctprofHigh { get; set; }
        public int? ReadAsianPacificIslander04pctprofLow { get; set; }
        public int? ReadAsianPacificIslander04pctprofHigh { get; set; }
        public int? ReadAsianPacificIslander05pctprofLow { get; set; }
        public int? ReadAsianPacificIslander05pctprofHigh { get; set; }
        public int? ReadAsianPacificIslander06pctprofLow { get; set; }
        public int? ReadAsianPacificIslander06pctprofHigh { get; set; }
        public int? ReadAsianPacificIslander07pctprofLow { get; set; }
        public int? ReadAsianPacificIslander07pctprofHigh { get; set; }
        public int? ReadAsianPacificIslander08pctprofLow { get; set; }
        public int? ReadAsianPacificIslander08pctprofHigh { get; set; }
        public int? ReadAsianPacificIslanderAllGradesPctprofLow { get; set; }
        public int? ReadAsianPacificIslanderAllGradesPctprofHigh { get; set; }
        public int? ReadAsianPacificIslanderHspctprofLow { get; set; }
        public int? ReadAsianPacificIslanderHspctprofHigh { get; set; }
        public int? ReadBlack03pctprofLow { get; set; }
        public int? ReadBlack03pctprofHigh { get; set; }
        public int? ReadBlack04pctprofLow { get; set; }
        public int? ReadBlack04pctprofHigh { get; set; }
        public int? ReadBlack05pctprofLow { get; set; }
        public int? ReadBlack05pctprofHigh { get; set; }
        public int? ReadBlack06pctprofLow { get; set; }
        public int? ReadBlack06pctprofHigh { get; set; }
        public int? ReadBlack07pctprofLow { get; set; }
        public int? ReadBlack07pctprofHigh { get; set; }
        public int? ReadBlack08pctprofLow { get; set; }
        public int? ReadBlack08pctprofHigh { get; set; }
        public int? ReadBlackAllGradesPctprofLow { get; set; }
        public int? ReadBlackAllGradesPctprofHigh { get; set; }
        public int? ReadBlackhspctprofLow { get; set; }
        public int? ReadBlackhspctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites03pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites03pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites04pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites04pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites05pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites05pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites06pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites06pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites07pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites07pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilites08pctprofLow { get; set; }
        public int? ReadChildrenWithDisabilites08pctprofHigh { get; set; }
        public int? ReadChildrenWithDisabilitesAllGradesPctprofLow { get; set; }
        public int? ReadChildrenWithDisabilitesAllGradesPctprofHigh { get; set; }
        public int? ReadChildrenWithDisabiliteshspctprofLow { get; set; }
        public int? ReadChildrenWithDisabiliteshspctprofHigh { get; set; }
        public int? ReadF03pctprofLow { get; set; }
        public int? ReadF03pctprofHigh { get; set; }
        public int? ReadF04pctprofLow { get; set; }
        public int? ReadF04pctprofHigh { get; set; }
        public int? ReadF05pctprofLow { get; set; }
        public int? ReadF05pctprofHigh { get; set; }
        public int? ReadF06pctprofLow { get; set; }
        public int? ReadF06pctprofHigh { get; set; }
        public int? ReadF07pctprofLow { get; set; }
        public int? ReadF07pctprofHigh { get; set; }
        public int? ReadF08pctprofLow { get; set; }
        public int? ReadF08pctprofHigh { get; set; }
        public int? ReadFAllGradesPctprofLow { get; set; }
        public int? ReadFAllGradesPctprofHigh { get; set; }
        public int? ReadFhspctprofLow { get; set; }
        public int? ReadFhspctprofHigh { get; set; }
        public int? ReadHispanic03pctprofLow { get; set; }
        public int? ReadHispanic03pctprofHigh { get; set; }
        public int? ReadHispanic04pctprofLow { get; set; }
        public int? ReadHispanic04pctprofHigh { get; set; }
        public int? ReadHispanic05pctprofLow { get; set; }
        public int? ReadHispanic05pctprofHigh { get; set; }
        public int? ReadHispanic06pctprofLow { get; set; }
        public int? ReadHispanic06pctprofHigh { get; set; }
        public int? ReadHispanic07pctprofLow { get; set; }
        public int? ReadHispanic07pctprofHigh { get; set; }
        public int? ReadHispanic08pctprofLow { get; set; }
        public int? ReadHispanic08pctprofHigh { get; set; }
        public int? ReadHispanicAllGradesPctprofLow { get; set; }
    }
}
